version: '3'
services:
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./Nginx/core:/etc/nginx/conf.d
      - ./Nginx/www:/var/www/
      - ./Nginx/Logs:/var/log/nginx/
      - ./Nginx/html:/usr/share/nginx/html/
    links: 
      - php
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql
# Пропишем настройки, предлагаю использовать вместо mypassword более сложный пароль, он пренадлежит root
   # environment:
    #  - MYSQL_ROOT_PASSWORD=mypassword
    #  - MYSQL_DATABASE=magento2
    #  - MYSQL_USER=magento2
    #  - MYSQL_PASSWORD=magento2
    volumes:
      - ./MySQL:/var/lib/mysql
  php:
# Билдим с помощью dockerfile указав директорию где он лежит
    build: ./PHP
    container_name: php-fpm
    restart: always
    volumes:
      - ./Nginx/www:/var/www
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8090:80
    links:
      - mysql:db
volumes:
  bluetoothcache: