version: '2'
services:
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./bluetooth-audio
    privileged: true
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
volumes:
  bluetoothcache: